name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t portfolio .

      - name: Tag Docker Image
        run: |
          docker tag portfolio:latest 837402981095.dkr.ecr.ap-southeast-2.amazonaws.com/portfolio:latest

      - name: Push Docker Image
        run: |
          docker push 837402981095.dkr.ecr.ap-southeast-2.amazonaws.com/portfolio:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 837402981095.dkr.ecr.ap-southeast-2.amazonaws.com

            docker pull 837402981095.dkr.ecr.ap-southeast-2.amazonaws.com/portfolio:latest

            docker stop portfolio || true
            docker rm portfolio || true

            docker run -d --name portfolio --restart unless-stopped -p 80:80 837402981095.dkr.ecr.ap-southeast-2.amazonaws.com/portfolio:latest